# Generated by Django 4.0.3 on 2024-08-22 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarysystem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='model_num',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='serial_num',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='tag_num',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
