# Generated by Django 5.1 on 2024-09-07 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarysystem', '0002_equipment_model_num_equipment_serial_num_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentequipment',
            name='equipment',
        ),
        migrations.AddField(
            model_name='studentequipment',
            name='equipment',
            field=models.ManyToManyField(to='librarysystem.equipment'),
        ),
    ]
