# Generated by Django 5.1 on 2024-09-19 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarysystem', '0003_remove_studentequipment_equipment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentequipment',
            name='equipment',
        ),
        migrations.AddField(
            model_name='studentequipment',
            name='equipment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='librarysystem.equipment'),
            preserve_default=False,
        ),
    ]
