# Generated by Django 4.0.3 on 2024-07-08 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarysystem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('tag_num', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('purchase_date', models.DateField()),
                ('is_available', models.BooleanField(default=True)),
                ('location', models.CharField(max_length=40)),
                ('condition', models.CharField(choices=[('new', 'New'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor')], default='new', max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
