# Generated by Django 4.0.3 on 2024-07-14 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('librarysystem', '0005_alter_equipment_condition'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrow_date', models.DateTimeField(auto_now_add=True)),
                ('return_date', models.DateTimeField(blank=True, null=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='librarysystem.equipment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='librarysystem.student')),
            ],
        ),
        migrations.DeleteModel(
            name='IssuedBook',
        ),
    ]
