# Generated by Django 4.0.3 on 2024-07-17 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarysystem', '0006_studentequipment_delete_issuedbook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='tag_num',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
