# Generated by Django 4.0.3 on 2024-07-20 13:31

from django.db import migrations, models
import librarysystem.models


class Migration(migrations.Migration):

    dependencies = [
        ('librarysystem', '0007_alter_equipment_tag_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentequipment',
            name='return_date',
            field=models.DateTimeField(blank=True, default=librarysystem.models.default_return_by, null=True),
        ),
    ]
