# Generated by Django 4.0.3 on 2024-07-20 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarysystem', '0008_alter_studentequipment_return_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentequipment',
            name='date_returned',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
